# generated by datamodel-codegen:
#   filename:  vegaspec.json
#   timestamp: 2024-05-12T22:42:44+00:00

from __future__ import annotations

from pydantic import RootModel

from eidos._basemodel import EidosModel


class Model(EidosModel):
    pass


class VegaSpec(EidosModel):
    pass


class TopLevelSpec(RootModel[VegaSpec]):
    root: VegaSpec
