# generated by datamodel-codegen:
#   filename:  worldlayers/feature_overlay.json
#   timestamp: 2024-05-15T05:06:01+00:00

from __future__ import annotations

from typing import Optional

from pydantic import ConfigDict

from eidos._basemodel import EidosModel

from ..core import state
from ..viewnodes import world


class FeatureLayer(EidosModel):
    """
    Specification for Feature overlay layer
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    hoverInfo: Optional[world.HoverInfo] = None
    timeSelect: Optional[state.TimeSelect] = None
    geometry: Optional[world.Geometry] = None
    colormap: Optional[world.Colormap] = None
    style: world.StyleAccessor
