# generated by datamodel-codegen:
#   filename:  worldlayers/grid.json
#   timestamp: 2024-05-17T07:49:31+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import ConfigDict, RootModel

from ..viewnodes import world
from ..viewnodes.world import LayerSpec


class GridLayerDatakeys(RootModel[Any]):
    root: Any


class Contour(RootModel[Any]):
    root: Any


class Particles(RootModel[Any]):
    root: Any


class Pcolor(RootModel[Any]):
    root: Any


class GridLayerSpec(LayerSpec):
    """
    Specification for Grid Overlay model settings
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    dataKeys: GridLayerDatakeys
    hoverInfo: Optional[world.HoverInfo] = None
    legend: Optional[world.Colormap] = None
    colormap: world.Colormap
    pcolor: Optional[Pcolor] = None
    particles: Optional[Particles] = None
    partmesh: Optional[Particles] = None
    contour: Optional[Contour] = None
    scale: Optional[float] = 1
    offset: Optional[float] = 1
    units: Optional[str] = None
    precision: Optional[float] = 1
    minzoom: Optional[float] = 1
    maxzoom: Optional[float] = 18
    landmask: Optional[bool] = None
