# generated by datamodel-codegen:
#   filename:  worldlayers/track_overlay.json
#   timestamp: 2024-05-15T05:06:01+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import ConfigDict, Field

from eidos._basemodel import EidosModel

from ..viewnodes import world


class Track(EidosModel):
    key: Optional[str] = Field(None, title='Track key')
    """
    Data field to use as key for grouping tracks
    """
    history: Optional[str] = Field('PT1H', title='Track history')
    """
    Length of previous positions to show (ISO8601 period)
    """


class TrackLayerDatakeys(EidosModel):
    """
    Mapping from data variables to lon,lat and time
    """

    model_config = ConfigDict(
        extra='allow',
    )
    x: str
    y: str
    t: str


class TrackLayer(EidosModel):
    """
    Specification for Track overlay layer
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    dataKeys: TrackLayerDatakeys
    hoverInfo: Optional[world.HoverInfo] = None
    colormap: Optional[world.Colormap] = None
    style: Optional[Dict[str, Any]] = None
    track: Track
    legend: Optional[world.Legend] = None
