# generated by datamodel-codegen:
#   filename:  panel.json
#   timestamp: 2026-05-11T06:37:09+00:00

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from ._basemodel import EidosModel
from pydantic import Field

from . import common
from .node import derived, document, grid, menu, plot, world


class TriggerPattern(EidosModel):
    """
    A single event-matching pattern. Deep subset-matched against the event; unspecified fields are wildcards.
    """

    action: Optional[str] = None
    """
    Event action to match (e.g. 'click', 'rightClick', 'doubleClick', 'hover', 'drop', 'activateControl'). Glob patterns supported.
    """
    source: Optional[str] = None
    """
    Event source path to match. Layer interactions: '/root/children/#layerId'. Control activations: '/root/children/#controlGroupId/children/#controlId'. Glob patterns supported (e.g. '/root/children/*' matches any child layer).
    """
    data: Optional[Dict[str, Any]] = None
    """
    Subset of event data fields to match against. Only the fields you specify need to be present and equal in the event.
    """


class EidosPanel(EidosModel):
    """
    A panel is a floating window rendered on top of its parent element. It can contain any node type (world, plot, document, grid, or menu). Panels can be opened by a panelopen control button, by a spec patch, or automatically by an event trigger.
    """

    id: str
    """
    Unique ID of the panel. Referenced by panelopen controls via config.panelId.
    """
    nodeType: Literal['panel'] = 'panel'
    open: Optional[bool] = False
    """
    Initial open state. Set to true to open the panel on load. Can also be set via specPatch at runtime to open or close the panel programmatically — the state is one-way (patching open:false closes the panel, but user-initiated closes do not write back to spec).
    """
    node: Union[
        world.World, plot.Plot, document.Document, grid.Grid, menu.Menu, derived.Derived
    ]
    """
    The content node rendered inside the panel.
    """
    trigger: Optional[List[TriggerPattern]] = Field(None, min_length=1)
    """
    Event patterns that automatically open this panel. The panel opens when **any** pattern in the array matches the most recent event on the event bus (logical OR). Each pattern is compared as a deep subset against the event — the pattern matches when all fields it specifies are equal to the corresponding fields on the event. String values support glob pattern matching. Unspecified fields are ignored.

    Use a single-element array for a single trigger; use multiple elements when distinct event shapes (different actions, sources, or data filters) should all open the same panel.

    Event fields available to match against:
    - action (string): type of event — 'click', 'rightClick', 'doubleClick', 'drop', 'hover', 'viewStateChange', 'activateControl', etc.
    - source (string, glob-matched): path identifying what produced the event. Layer interaction sources follow the pattern '/{path}/children/#{layerId}' (e.g. '/root/children/#wave-height'). Use glob wildcards to match multiple sources (e.g. '/root/children/*').
    - data (object): event payload — subset-match any fields you care about.
    - coordinate ([number, number]): [longitude, latitude] of the interaction point.

    Examples:
      Open on any click on a specific layer:
        [ { "action": "click", "source": "/root/children/#my-layer" } ]

      Open from either of two layers:
        [
          { "action": "click", "source": "/root/children/#layer-a" },
          { "action": "click", "source": "/root/children/#layer-b" }
        ]

      Open when a specific control is activated:
        [ { "action": "activateControl", "source": "/root/children/#controls/children/#draw-tool" } ]
    """
    exclusive: Optional[bool] = False
    """
    If true, opening this panel closes all other currently open panels. Useful for modal-style panels that should have the user's full attention.
    """
    height: Optional[common.CssSpec] = None
    """
    Height of the panel. CSS string (e.g. '300px', '50%') or a number interpreted as pixels.
    """
    width: Optional[common.CssSpec] = None
    """
    Width of the panel. CSS string (e.g. '400px', '30%') or a number interpreted as pixels.
    """
    position: Optional[common.Position] = Field(
        default_factory=lambda: common.Position.model_validate(
            {'top': None, 'left': None, 'bottom': None, 'right': None}
        )
    )
    """
    Position of the panel relative to its parent element. Specify top/left/right/bottom as CSS strings or pixel numbers. If no position is given the panel is centred. For world overlay panels, position is relative to the map container.
    """
    title: Optional[str] = None
    """
    Title displayed in the panel header bar.
    """
    closable: Optional[bool] = True
    """
    Whether the user can dismiss the panel. When false, the close button is hidden and the panel can only be closed programmatically (via specPatch or a closePanel event). Defaults to true.
    """


import sys as _sys
_panel_ns = {"panel": _sys.modules[__name__]}
world.World.model_rebuild(_types_namespace=_panel_ns)
grid.Grid.model_rebuild(_types_namespace=_panel_ns)
menu.Menu.model_rebuild(_types_namespace=_panel_ns)
EidosPanel.model_rebuild()
