# generated by datamodel-codegen:
#   filename:  worldlayers/feature_overlay.json
#   timestamp: 2024-05-12T23:25:22+00:00

from __future__ import annotations

from typing import Optional

from pydantic import ConfigDict

from eidos._basemodel import EidosModel

from ..core import state
from ..viewnodes import world


class FeatureLayerDatakeys(EidosModel):
    """
    Mapping from data variables to geometry and time
    """

    model_config = ConfigDict(
        extra="allow",
    )
    t: Optional[str] = None


class FeatureLayer(EidosModel):
    """
    Specification for Feature overlay layer
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    dataKeys: FeatureLayerDatakeys
    hoverInfo: Optional[world.HoverInfo] = None
    timeSelect: Optional[state.TimeSelect] = None
    geometry: Optional[world.Geometry] = None
    colormap: Optional[world.Colormap] = None
    style: Optional[world.StyleAccessor] = None
