# generated by datamodel-codegen:
#   filename:  worldlayers/grid_overlay.json
#   timestamp: 2024-05-12T22:42:44+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import ConfigDict, RootModel

from eidos._basemodel import EidosModel

from ..viewnodes import world


class Baseprops(EidosModel):
    altitude: Optional[float] = None
    zscale: Optional[float] = None
    colormap: Optional[bool] = None
    opacity: Optional[float] = 1.0
    color: Optional[List[Any]] = None


class Pcolor(RootModel[Baseprops]):
    root: Baseprops


class Particles(RootModel[Baseprops]):
    root: Baseprops


class Partmesh(RootModel[Baseprops]):
    root: Baseprops


class Contour(Baseprops):
    levels: Optional[List[float]] = None
    linewidth: Optional[int] = 1


class GridLayerDatakeys(EidosModel):
    x: str
    y: str
    c: Optional[str] = None
    d: Optional[str] = None
    m: Optional[str] = None
    u: Optional[str] = None
    v: Optional[str] = None


class GridLayer(EidosModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    datakeys: GridLayerDatakeys
    hoverInfo: Optional[world.HoverInfo] = None
    legend: Optional[world.Colormap] = None
    colormap: world.Colormap
    pcolor: Optional[Pcolor] = None
    particles: Optional[Particles] = None
    partmesh: Optional[Particles] = None
    contour: Optional[Contour] = None
    scale: Optional[float] = 1
    offset: Optional[float] = 1
    units: Optional[str] = None
    precision: Optional[float] = 1
    minzoom: Optional[float] = 1
    maxzoom: Optional[float] = 18
    landmask: Optional[bool] = None
