# generated by datamodel-codegen:
#   filename:  worldlayers/track_overlay.json
#   timestamp: 2024-05-12T22:42:44+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import ConfigDict, Field

from eidos._basemodel import EidosModel

from ..viewnodes import world


class Track(EidosModel):
    key: Optional[str] = Field(
        None,
        description='Data field to use as key for grouping tracks',
        title='Track key',
    )
    history: Optional[str] = Field(
        'PT1H',
        description='Length of previous positions to show (ISO8601 period)',
        title='Track history',
    )


class TrackLayerDatakeys(EidosModel):
    model_config = ConfigDict(
        extra='allow',
    )
    x: str
    y: str
    t: str


class TrackLayer(EidosModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    datakeys: TrackLayerDatakeys
    hoverInfo: Optional[world.HoverInfo] = None
    colormap: Optional[world.Colormap] = None
    style: Optional[Dict[str, Any]] = None
    track: Track
    legend: Optional[world.Legend] = None
