# generated by datamodel-codegen:
#   filename:  node/derived.json
#   timestamp: 2026-05-11T06:37:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, List, Literal, Optional

from eidosxr._basemodel import EidosModel
from pydantic import ConfigDict, Field, constr


class Op(str, Enum):
    """
    Patch operation.
    """

    add = 'add'
    remove = 'remove'
    replace = 'replace'
    move = 'move'
    copy = 'copy'
    test = 'test'


class Patch(EidosModel):
    op: Op
    """
    Patch operation.
    """
    path: constr(pattern=r'^[^/].*')
    """
    Subtree-relative path using RFC 6901 segments (e.g. 'plotSpec/layer/0/encoding/color/value'). Must NOT start with '/' — leading-slash 'absolute' paths are reserved for future cross-subtree patches and rejected in v1.
    """
    value: Optional[Any] = None
    """
    Replacement value for add / replace / test operations.
    """
    from_: Optional[str] = Field(None, alias='from')
    """
    Source path for move / copy operations.
    """


class Derived(EidosModel):
    """
    A derived node references another node in the same spec by ID and applies a list of patches at render time. Use it to reuse a chart, document, panel, or other node with small variations (e.g. a different data source or field) without duplicating the source subtree. Resolution and patching happen lazily at render time — derived nodes inside unrendered branches cost nothing, and edits to the source node propagate naturally on the next render.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., examples=['chart-copy-1', 'panel-variant-a'])
    """
    Unique identifier for this derived node within the specification. Replaces the source node's root ID in the rendered subtree, and prefixes every descendant ID so multiple derivations of the same source do not collide.
    """
    title: Optional[str] = None
    """
    Optional human-readable title for this derived node.
    """
    nodeType: Literal['derived']
    """
    Node type identifier. Must be 'derived'.
    """
    source: str = Field(..., examples=['bar-chart-1', 'main-panel'])
    """
    ID of the source node to derive from. The renderer looks up this ID in the current spec at render time, deep-clones the source subtree, prefixes descendant IDs with this derived node's ID, rewrites internal cross-references, applies the patches, and renders the result. The root of the spec cannot be a derived node, and the source itself cannot be a derived node.
    """
    patches: Optional[List[List[Patch]]] = []
    """
    Ordered list of JSON Patch documents applied to the resolved source subtree after ID and reference rewriting. Paths are subtree-relative — they use RFC 6901 segment syntax (e.g. 'plotSpec/layer/0/data/name') and must NOT start with a leading '/'. The leading-slash form is the JSON Pointer 'absolute against document root' notation and is reserved for future cross-subtree patches; v1 rejects it so the convention mismatch surfaces immediately.
    """
