# generated by datamodel-codegen:
#   filename:  node/menu.json
#   timestamp: 2026-05-11T06:37:09+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional, Union

from eidosxr._basemodel import EidosModel
from pydantic import ConfigDict

from . import derived, document, grid, plot, world


class Position(str, Enum):
    """
    Location of menu relative to content
    """

    top = 'top'
    left = 'left'
    bottom = 'bottom'
    right = 'right'


class MenuLayoutItem(EidosModel):
    """
    Configuration of nodes in menu layout
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    label: Union[str, List[str]]
    icon: Optional[Union[str, List[str]]] = None


class Menu(EidosModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique id of the node
    """
    nodeType: Literal['menu'] = 'menu'
    activeItem: Optional[str] = None
    position: Optional[Position] = 'top'
    """
    Location of menu relative to content
    """
    open: Optional[bool] = True
    """
    Whether menu is open
    """
    children: List[
        Union[world.World, plot.Plot, document.Document, grid.Grid, derived.Derived]
    ]
    openOnMouseOver: Optional[bool] = False
    menuLayout: List[MenuLayoutItem]


# model_rebuild() called in panel.py after EidosPanel is defined to break circular import
