# generated by datamodel-codegen:
#   filename:  node/worldlayer/pointcloud.json
#   timestamp: 2026-06-29T02:44:25+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union

from oceanum.eidos._basemodel import EidosModel
from pydantic import ConfigDict, Field, confloat

from . import common as common_1


class PointCloudLayerDatakeys(EidosModel):
    """
    Mapping from data variables to optional point fields (value, normals). Point positions (x/y/z) and the time coordinate are resolved at runtime from the datasource's own coordinate keys (data.coordkeys), following the scenegraph convention — not from these datakeys.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    value: Optional[str] = None
    """
    Value variable mapped to colour via the colormap
    """
    nx: Optional[str] = None
    """
    Point normal x-component variable (for lighting)
    """
    ny: Optional[str] = None
    """
    Point normal y-component variable (for lighting)
    """
    nz: Optional[str] = None
    """
    Point normal z-component variable (for lighting)
    """


class SizeUnits(str, Enum):
    """
    Units for pointSize.
    """

    pixels = 'pixels'
    meters = 'meters'
    common = 'common'


class PointCloudStyle(EidosModel):
    """
    Point cloud styling. Properties not listed here are passed through to the deck.gl PointCloudLayer.
    """

    model_config = ConfigDict(
        extra='allow',
    )
    getColor: Optional[common_1.StyleAccessor] = None
    """
    Per-point colour. Use a colormapper function accessor over the value variable, or a constant colour. Overrides the default colormap colouring.
    """
    pointSize: Optional[float] = 2
    """
    Point radius, in sizeUnits.
    """
    sizeUnits: Optional[SizeUnits] = 'pixels'
    """
    Units for pointSize.
    """
    material: Optional[Union[bool, Dict[str, Any]]] = True
    """
    deck.gl lighting material; set to false to disable lighting.
    """
    coordinateOrigin: Optional[List[float]] = Field(None, max_length=3, min_length=2)
    """
    When set, positions are interpreted as local metre offsets [lng, lat, alt] around this origin instead of lng/lat.
    """
    opacity: Optional[confloat(ge=0.0, le=1.0)] = 1
    """
    Layer opacity.
    """


class PointCloudLayer(EidosModel):
    """
    World layer for visualizing 3D point clouds (deck.gl PointCloudLayer). Renders a set of points from a datasource exposing x/y/z coordinates, optionally coloured by a value variable through a colormap and lit using per-point normals. Suitable for LiDAR, bathymetric soundings, particle ensembles, or any scattered 3D point data.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    layerType: Literal['pointcloud']
    """
    Layer type identifier. Must be 'pointcloud' for 3D point cloud visualizations.
    """
    datakeys: PointCloudLayerDatakeys
    """
    Mapping of data variables to point coordinates and optional value/normal fields.
    """
    legend: Optional[common_1.Legend] = None
    """
    Configuration for the colour-scale legend display.
    """
    colormap: Optional[common_1.Colormap] = None
    """
    Colour mapping that translates the value variable to per-point colours.
    """
    style: Optional[PointCloudStyle] = None
    """
    Visual styling for the point cloud.
    """
