# generated by datamodel-codegen:
#   filename:  vegaspec.json
#   timestamp: 2024-05-15T05:06:01+00:00

from __future__ import annotations

from pydantic import RootModel

from eidos._basemodel import EidosModel


class Model(EidosModel):
    """
    Vega or Vega-Lite specification
    """


class VegaSpec(EidosModel):
    """
    Top-level specification of a Vega or Vega-Lite visualization
    """


class TopLevelSpec(RootModel[VegaSpec]):
    root: VegaSpec
