# generated by datamodel-codegen:
#   filename:  common.json
#   timestamp: 2026-06-29T02:44:25+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional, Union

from oceanum.eidos._basemodel import EidosModel
from pydantic import ConfigDict, Field, RootModel, constr


class EidosCommonDefinitions(RootModel[Any]):
    root: Any = Field(..., title='Eidos common definitions')


class Kind(str, Enum):
    """
    Type of runtime source to resolve the value from.
    """

    event = 'event'
    selection = 'selection'
    parameter = 'parameter'


class ValueFrom(EidosModel):
    """
    Reference a value from runtime state such as an event, selection, or parameter. The path is resolved against the referenced source object.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Kind
    """
    Type of runtime source to resolve the value from.
    """
    source: str
    """
    Identifier of the runtime source. For events this is typically the source path or named event source; for selections and parameters this is the selection or parameter name.
    """
    action: Optional[str] = Field(
        None, examples=['click', 'rightClick', 'doubleClick', 'changeMenuItem']
    )
    """
    Optional event action discriminator when kind is 'event'.
    """
    path: str
    """
    Dot-path to the desired value within the resolved source object, for example 'data.siteId', 'data.geometry', or 'object.geometry'.
    """
    required: Optional[bool] = False
    """
    Whether resolution failure should be treated as an error instead of yielding an empty value.
    """


class Resolvable(EidosModel):
    """
    Wrapper object used by schemas that allow literal values to be replaced by a dynamic runtime binding.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    valueFrom: ValueFrom


class CurrentTime(RootModel[Union[datetime, constr(pattern=r'^-?P')]]):
    root: Union[datetime, constr(pattern=r'^-?P')] = Field(..., title='Current time')
    """
    Time of current node view. Supports ISO 8601 date-time (e.g., '2025-01-01T00:00:00Z') or ISO 8601 duration relative to now (e.g., 'PT0H' for now, '-P1D' for 1 day ago, 'P7D' for 7 days ahead)
    """


class LevelControl(EidosModel):
    """
    Level/depth control for selecting vertical levels in data
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    range: List[float] = Field(..., max_length=2, min_length=2)
    """
    Level range as [min, max]. Used with step to generate discrete levels.
    """
    step: Optional[float] = Field(None, title='Level step')
    """
    Step size between levels when using range
    """
    levels: Optional[List[float]] = None
    """
    Explicit array of discrete level values. If provided, overrides range/step.
    """
    units: Optional[str] = Field(None, title='Level units')
    """
    Unit label for levels (e.g., 'm', 'hPa', 'ft')
    """
    label: Optional[str] = Field(None, title='Control label')
    """
    Label displayed above the level selector
    """
    default: Optional[float] = Field(None, title='Default level')
    """
    Initial level value
    """


class Timezone(RootModel[Optional[str]]):
    root: Optional[str]


class CssSpec(RootModel[Optional[Union[int, str]]]):
    root: Optional[Union[int, str]] = Field(..., title='CSS spec')
    """
    CSS string or pixels as integer or null
    """


class Position(EidosModel):
    top: Optional[CssSpec] = None
    left: Optional[CssSpec] = None
    bottom: Optional[CssSpec] = None
    right: Optional[CssSpec] = None


class TimeControl(EidosModel):
    """
    Time control for selecting the current time with a slider and optional play/pause buttons for animation
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    range: List[str] = Field(..., max_length=2, min_length=2)
    """
    Time range of time control. Each value can be an ISO 8601 date-time or duration (e.g., ['-P1D', 'P7D'] for 1 day ago to 7 days ahead)
    """
    step: Optional[Union[float, str]] = Field(None, title='Time step')
    """
    Size of time selector increments. Also used for rounding duration-based times. Can be a number (seconds) or ISO 8601 duration (e.g., 'PT1H' for 1 hour)
    """
    timezone: Optional[Timezone] = None
    zoomable: Optional[bool] = Field(True, title='Zoomable time axis')
    """
    When true, the time axis can be zoomed with the mouse wheel, double-click, and right-click. Defaults to true.
    """
    lockToNow: Optional[bool] = Field(False, title='Lock to current time')
    """
    When true, the time selector starts locked to the current real-world (wall-clock) time and auto-advances to follow it. Any manual interaction with the slider breaks the lock; it can be re-enabled via the control. Defaults to false.
    """
