# generated by datamodel-codegen:
#   filename:  vegaspec.json
#   timestamp: 2024-05-28T21:53:23+00:00

from __future__ import annotations

from oceanum.eidos._basemodel import EidosModel
from pydantic import RootModel


class Model(EidosModel):
    """
    Vega or Vega-Lite specification
    """


class VegaSpec(EidosModel):
    """
    Top-level specification of a Vega or Vega-Lite visualization
    """


class TopLevelSpec(RootModel[VegaSpec]):
    root: VegaSpec
