# generated by datamodel-codegen:
#   filename:  viewnodes/document.json
#   timestamp: 2024-05-28T21:53:23+00:00

from __future__ import annotations

from typing import Optional

from oceanum.eidos._basemodel import EidosModel
from pydantic import ConfigDict


class DocumentView(EidosModel):
    """
    Specification for document panel
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    content: str
    """
    Document content as templated markdown
    """
    style: Optional[str] = None
    """
    Document style
    """
