# generated by datamodel-codegen:
#   filename:  node/worldlayer/common.json
#   timestamp: 2026-05-11T06:37:09+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional, Union

from eidosxr._basemodel import EidosModel
from pydantic import AnyUrl, ConfigDict, Field, RootModel


class WorldlayerCommonProperties(EidosModel):
    """
    Common properties for worldlayer nodes
    """


class ScaledColormap(EidosModel):
    """
    Predefined colormap
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    scale: List[str]
    """
    Scale of the colormap
    """
    domain: List[Union[float, str]]
    """
    Domain of the colormap (min and max values or values )
    """


class Name(str, Enum):
    """
    Name of the preset colormap
    """

    turbo = 'turbo'
    viridis = 'viridis'
    cividis = 'cividis'
    inferno = 'inferno'
    magma = 'magma'
    plasma = 'plasma'
    d3 = 'd3'
    g10 = 'g10'
    t10 = 't10'
    alphabet = 'alphabet'
    dark24 = 'dark24'
    light24 = 'light24'
    twilight = 'twilight'
    icefire = 'icefire'
    edge = 'edge'
    phase = 'phase'
    hsv = 'hsv'
    mrybm = 'mrybm'
    mygbm = 'mygbm'
    turbid = 'turbid'
    thermal = 'thermal'
    haline = 'haline'
    solar = 'solar'
    ice = 'ice'
    gray = 'gray'
    oxy = 'oxy'
    deep = 'deep'
    dense = 'dense'
    algae = 'algae'
    matter = 'matter'
    speed = 'speed'
    amp = 'amp'
    tempo = 'tempo'
    balance = 'balance'
    delta = 'delta'
    curl = 'curl'
    wind = 'wind'
    wave = 'wave'
    purples = 'purples'
    blues = 'blues'
    greens = 'greens'
    oranges = 'oranges'
    reds = 'reds'
    ylorbr = 'ylorbr'
    ylorrd = 'ylorrd'
    orrd = 'orrd'
    purd = 'purd'
    rdpu = 'rdpu'
    bupu = 'bupu'
    pubu = 'pubu'
    pubugn = 'pubugn'
    gnbu = 'gnbu'
    bugn = 'bugn'
    ylgnbu = 'ylgnbu'
    ylgn = 'ylgn'
    greys = 'greys'
    spectral = 'spectral'
    rdylgn = 'rdylgn'
    rdbu = 'rdbu'
    piyg = 'piyg'
    prgn = 'prgn'
    rdylbu = 'rdylbu'
    brbg = 'brbg'
    rdgy = 'rdgy'
    set1 = 'set1'
    pastel1 = 'pastel1'
    dark2 = 'dark2'
    set2 = 'set2'
    pastel2 = 'pastel2'
    set3 = 'set3'


class PresetColormap(EidosModel):
    """
    Predefined colormap
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    name: Name
    """
    Name of the preset colormap
    """
    domain: Optional[List[float]] = Field(None, max_length=20, min_length=2)
    """
    Domain of the preset colormap (min and max values)
    """


class Color(RootModel[Union[List[float], str]]):
    root: Union[List[float], str] = Field(..., title='Color')
    """
    Color definition
    """


class StyleAccessorString(RootModel[str]):
    root: str = Field(..., title='Style accessor constant string')
    """
    Constant value
    """


class StyleAccessorNumber(RootModel[float]):
    root: float = Field(..., title='Style accessor constant number')
    """
    Constant value
    """


class StyleAccessorArray(RootModel[List[float]]):
    """
    Array of constant values
    """

    root: List[float] = Field(..., title='Style accessor constant array')
    """
    Array of constant values
    """


class StyleAccessorTemplate(EidosModel):
    """
    Template accessor
    """

    template: str
    """
    Template string
    """


class StyleAccessorFunction(EidosModel):
    """
    Accessor function
    """

    function: str
    """
    Accessor function identifier
    """
    args: List[str]
    """
    Arguments for accessor function
    """


class LegendSpec(EidosModel):
    """
    Legend properties
    """

    title: Optional[str] = None
    """
    Legend title
    """
    labels: Optional[List[Union[str, float]]] = None
    """
    Legend labels
    """
    url: Optional[AnyUrl] = None
    """
    URL to an external legend image
    """


class Legend(RootModel[Optional[Union[LegendSpec, bool]]]):
    root: Optional[Union[LegendSpec, bool]] = Field(..., title='Legend definition')
    """
    Legend properties
    """


class Colormap(RootModel[Union[PresetColormap, ScaledColormap]]):
    root: Union[PresetColormap, ScaledColormap] = Field(..., title='Colormap')
    """
    Scale and domain argument for chroma.scale colormap definition
    """


class StyleAccessor(
    RootModel[
        Union[
            StyleAccessorString,
            StyleAccessorNumber,
            StyleAccessorFunction,
            StyleAccessorArray,
            StyleAccessorTemplate,
        ]
    ]
):
    root: Union[
        StyleAccessorString,
        StyleAccessorNumber,
        StyleAccessorFunction,
        StyleAccessorArray,
        StyleAccessorTemplate,
    ] = Field(..., title='Style accessor definition')
    """
    Style properties
    """
