# generated by datamodel-codegen:
#   filename:  node/document.json
#   timestamp: 2026-06-29T02:44:25+00:00

from __future__ import annotations

from typing import Literal, Optional

from oceanum.eidos._basemodel import EidosModel
from pydantic import ConfigDict

from .. import theme


class DocumentStyle(EidosModel):
    """
    Document style overrides
    """

    text: Optional[theme.TextStyle] = None


class Document(EidosModel):
    """
    Specification for document node
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    """
    Unique id of the node
    """
    title: Optional[str] = None
    """
    Title of the document
    """
    nodeType: Literal['document'] = 'document'
    content: str
    """
    Document content as templated markdown
    """
    style: Optional[DocumentStyle] = None
