# generated by datamodel-codegen:
#   filename:  viewnodes/document.json
#   timestamp: 2024-05-12T22:42:44+00:00

from __future__ import annotations

from typing import Optional

from pydantic import ConfigDict, Field

from eidos._basemodel import EidosModel


class DocumentView(EidosModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str = Field(..., description='Document content as templated markdown')
    style: Optional[str] = Field(None, description='Document style')
