# generated by datamodel-codegen:
#   filename:  viewnodes/document.json
#   timestamp: 2024-05-12T23:25:22+00:00

from __future__ import annotations

from typing import Optional

from pydantic import ConfigDict

from eidos._basemodel import EidosModel


class DocumentView(EidosModel):
    """
    Specification for document panel
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    content: str
    """
    Document content as templated markdown
    """
    style: Optional[str] = None
    """
    Document style
    """
