# generated by datamodel-codegen:
#   filename:  viewnodes/plot.json
#   timestamp: 2024-05-12T23:25:22+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import ConfigDict

from eidos._basemodel import EidosModel

from .. import vegaspec
from ..core import state


class PlotType(str, Enum):
    vega = 'vega'
    vega_lite = 'vega-lite'


class PlotView(EidosModel):
    """
    Specification for plot view environmental digital twin display and interaction
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    plotType: Optional[PlotType] = None
    plotSpec: vegaspec.TopLevelSpec
    """
    Plot specification for this panel as vega spec
    """
    currentTime: Optional[state.CurrentTime] = None
    currentContext: Optional[state.CurrentContext] = None
    canExport: Optional[bool] = None
    timeControl: Optional[state.TimeControl] = None
